In [1]:
import optuna 
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [3]:
df = pd.read_csv(url, names=columns)

In [4]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
# handling missing values 
import numpy as np

df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
(df==0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [7]:
cols_with_missing_values = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI','DiabetesPedigreeFunction']
df[cols_with_missing_values] = df[cols_with_missing_values].replace(0, np.nan)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [8]:
df.fillna(df.median(), inplace=True)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,125.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,29.0,125.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,125.0,30.4,0.315,23,0

In [9]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)

(537, 8)
(231, 8)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def objective(trial):
    # suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )
    
    score = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy').mean()
    return score

In [13]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
study.optimize(objective, n_trials=50)

[I 2026-06-29 12:35:32,655] A new study created in memory with name: no-name-17e7fb8a-f65b-4fc7-af8e-17c488d40519
[I 2026-06-29 12:35:32,976] Trial 0 finished with value: 0.7560055382485289 and parameters: {'n_estimators': 58, 'max_depth': 10}. Best is trial 0 with value: 0.7560055382485289.
[I 2026-06-29 12:35:33,698] Trial 1 finished with value: 0.7541190723433714 and parameters: {'n_estimators': 158, 'max_depth': 16}. Best is trial 0 with value: 0.7560055382485289.
[I 2026-06-29 12:35:34,440] Trial 2 finished with value: 0.7541190723433715 and parameters: {'n_estimators': 182, 'max_depth': 6}. Best is trial 0 with value: 0.7560055382485289.
[I 2026-06-29 12:35:34,971] Trial 3 finished with value: 0.7615610938040844 and parameters: {'n_estimators': 116, 'max_depth': 16}. Best is trial 3 with value: 0.7615610938040844.
[I 2026-06-29 12:35:35,630] Trial 4 finished with value: 0.7652474904811353 and parameters: {'n_estimators': 153, 'max_depth': 8}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:36,130] Trial 5 finished with value: 0.7559709241952233 and parameters: {'n_estimators': 109, 'max_depth': 12}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:36,631] Trial 6 finished with value: 0.7596919349255797 and parameters: {'n_estimators': 107, 'max_depth': 13}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:37,108] Trial 7 finished with value: 0.7652128764278296 and parameters: {'n_estimators': 108, 'max_depth': 8}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:37,967] Trial 8 finished with value: 0.7634129456559362 and parameters: {'n_estimators': 190, 'max_depth': 19}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:38,544] Trial 9 finished with value: 0.7578400830737279 and parameters: {'n_estimators': 128, 'max_depth': 17}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:39,089] Trial 10 finished with value: 0.7615784008307372 and parameters: {'n_estimators': 150, 'max_depth': 3}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:39,447] Trial 11 finished with value: 0.7652301834544826 and parameters: {'n_estimators': 83, 'max_depth': 8}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:39,745] Trial 12 finished with value: 0.7541363793700242 and parameters: {'n_estimators': 70, 'max_depth': 6}. Best is trial 4 with value: 0.7652474904811353.
[I 2026-06-29 12:35:40,105] Trial 13 finished with value: 0.7671339563862928 and parameters: {'n_estimators': 81, 'max_depth': 9}. Best is trial 13 with value: 0.7671339563862928.
[I 2026-06-29 12:35:40,775] Trial 14 finished with value: 0.7615610938040844 and parameters: {'n_estimators': 151, 'max_depth': 10}. Best is trial 13 with value: 0.7671339563862928.
[I 2026-06-29 12:35:41,097] Trial 15 finished with value: 0.7541017653167186 and parameters: {'n_estimators': 86, 'max_depth': 3}. Best is trial 13 with value: 0.7671339563862928.
[I 2026-06-29 12:35:41,840] Trial 16 finished with value: 0.7634302526825891 and parameters: {'n_estimators': 168, 'max_depth': 13}. Best is trial 13 with value: 0.7671339563862928.
[I 2026-06-29 12:35:42,386] Trial 17 finished with value: 0.7596919349255797 and parameters: {'n_estimators': 137, 'max_depth': 6}. Best is trial 13 with value: 0.7671339563862928.
[I 2026-06-29 12:35:42,778] Trial 18 finished with value: 0.7689858082381447 and parameters: {'n_estimators': 90, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:43,175] Trial 19 finished with value: 0.7503807545863621 and parameters: {'n_estimators': 88, 'max_depth': 10}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:43,451] Trial 20 finished with value: 0.7466770508826583 and parameters: {'n_estimators': 60, 'max_depth': 14}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:43,857] Trial 21 finished with value: 0.7633610245759778 and parameters: {'n_estimators': 94, 'max_depth': 8}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:44,180] Trial 22 finished with value: 0.7578400830737279 and parameters: {'n_estimators': 73, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:44,757] Trial 23 finished with value: 0.7596919349255797 and parameters: {'n_estimators': 137, 'max_depth': 7}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:44,973] Trial 24 finished with value: 0.7448251990308066 and parameters: {'n_estimators': 52, 'max_depth': 5}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:45,408] Trial 25 finished with value: 0.7522499134648668 and parameters: {'n_estimators': 96, 'max_depth': 10}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:45,747] Trial 26 finished with value: 0.7540844582900658 and parameters: {'n_estimators': 73, 'max_depth': 11}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:46,550] Trial 27 finished with value: 0.7541190723433715 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:47,145] Trial 28 finished with value: 0.7578227760470752 and parameters: {'n_estimators': 128, 'max_depth': 12}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:47,884] Trial 29 finished with value: 0.7652647975077882 and parameters: {'n_estimators': 166, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:48,647] Trial 30 finished with value: 0.7671166493596401 and parameters: {'n_estimators': 171, 'max_depth': 11}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:49,415] Trial 31 finished with value: 0.7652474904811353 and parameters: {'n_estimators': 173, 'max_depth': 11}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:50,135] Trial 32 finished with value: 0.7633956386292835 and parameters: {'n_estimators': 164, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:50,888] Trial 33 finished with value: 0.7671166493596401 and parameters: {'n_estimators': 174, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:51,698] Trial 34 finished with value: 0.7597092419522327 and parameters: {'n_estimators': 180, 'max_depth': 14}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:52,507] Trial 35 finished with value: 0.7597265489788854 and parameters: {'n_estimators': 189, 'max_depth': 7}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:53,043] Trial 36 finished with value: 0.7559882312218761 and parameters: {'n_estimators': 118, 'max_depth': 11}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:53,495] Trial 37 finished with value: 0.7615437867774316 and parameters: {'n_estimators': 100, 'max_depth': 13}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:54,129] Trial 38 finished with value: 0.7485635167878157 and parameters: {'n_estimators': 140, 'max_depth': 15}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:54,405] Trial 39 finished with value: 0.7484942886812045 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:54,757] Trial 40 finished with value: 0.7633956386292835 and parameters: {'n_estimators': 79, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:55,487] Trial 41 finished with value: 0.7671166493596401 and parameters: {'n_estimators': 161, 'max_depth': 9}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:56,240] Trial 42 finished with value: 0.7597092419522326 and parameters: {'n_estimators': 176, 'max_depth': 7}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:56,936] Trial 43 finished with value: 0.7652647975077882 and parameters: {'n_estimators': 156, 'max_depth': 10}. Best is trial 18 with value: 0.7689858082381447.
[I 2026-06-29 12:35:57,754] Trial 44 finished with value: 0.7690031152647975 and parameters: {'n_estimators': 188, 'max_depth': 8}. Best is trial 44 with value: 0.7690031152647975.
[I 2026-06-29 12:35:58,588] Trial 45 finished with value: 0.7690031152647975 and parameters: {'n_estimators': 191, 'max_depth': 8}. Best is trial 44 with value: 0.7690031152647975.
[I 2026-06-29 12:35:59,420] Trial 46 finished with value: 0.7633956386292835 and parameters: {'n_estimators': 196, 'max_depth': 8}. Best is trial 44 with value: 0.7690031152647975.
[I 2026-06-29 12:36:00,156] Trial 47 finished with value: 0.7559882312218761 and parameters: {'n_estimators': 188, 'max_depth': 5}. Best is trial 44 with value: 0.7690031152647975.
[I 2026-06-29 12:36:00,924] Trial 48 finished with value: 0.7615784008307372 and parameters: {'n_estimators': 184, 'max_depth': 7}. Best is trial 44 with value: 0.7690031152647975.
[I 2026-06-29 12:36:01,795] Trial 49 finished with value: 0.7634302526825891 and parameters: {'n_estimators': 195, 'max_depth': 20}. Best is trial 44 with value: 0.7690031152647975.

In [14]:
# printing best results

print(f"best trial accuracy: {study.best_trial.value}")
print(f"best hyperparameters: {study.best_trial.params}")

best trial accuracy: 0.7690031152647975
best hyperparameters: {'n_estimators': 188, 'max_depth': 8}

In [15]:
from sklearn.metrics import accuracy_score

best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)

test_accuracy = accuracy_score(y_test, y_pred)

print(f"Test Accuracy with best hyperparameters: {test_accuracy:.2f}")

Test Accuracy with best hyperparameters: 0.75